[package]
name = "fusumi"
version = "0.0.1"

[addresses]
fusumi_deployer = "0x37179705197d305198c8cfa6c98af4d0fa543d61d5876bd187ba6c76131b0f2a"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "main"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-token"
rev = "main"
